language: c

sudo: false

addons:
  apt:
    packages:
    - libgmp-dev

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

env:
- ARGS="--resolver lts-2"
- ARGS="--resolver lts-3"
- ARGS="--resolver lts-5"

script:
- stack $ARGS --no-terminal --install-ghc test

cache:
  directories:
  - $HOME/.stack

notifications:
  email: false
